language: python
matrix:
    include:
        - name: "Python 3.7 on Xenial Linux"
        python: 3.7
        dist: xenial
        - name: "Python 3.7 on Windows"
        os: windows
        language: shell
        before_install: choco install python
        env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - name: "Python 3.7 on macOS"
        os: osx
        osx_image: xcode10.2
        language: shell

# command to install dependencies
install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 install .
# command to run tests
script: pytest